### ISSUE TITLE
Test Case Coverage

### ISSUE THREAD

**Issue by skspall** [NickTsitlakidis/blog-browserify-testing#1]
Hi,

Won't say it an issue but an enhancement. I am unable to find coverage of js files using 'coverage' in preprocessors. 
Can you help me out with that?

Thanks,
SKSpall

**Comment by skspall** [comment]
I found this: browserify-istanbul.

May be this can help out.

**Comment by NickTsitlakidis** [comment]
The repository was created to include basic usage of unit testing and browserify. Test coverage was beyond the scope of the blog post. browserify-istanbul looks like the proper tool for the job though.

**Comment by skspall** [comment]
Ok. Thanks.
